### ISSUE TITLE
Add a code formatter like `black`

### ISSUE THREAD

**Issue by diego-garro** [KaratekHD/defrag#54]
Hi guys, do you want to add a code formatter like `black` to have a more readable code? Have in mind that this will format all the code to a unique one

**Comment by why-not-try-calmer** [comment]
Hello deigo, it's always a good idea to use a code formatter. My favorite one is `autopep8`, because it's very close to the official recommended formatting. I think the end result is not very different from `black`. In a big, industrial project it would be certainly not doable to work with different formatters, but here I think it's OK if everyone picks their favorite formatter. As you will see if it's not already the case, we have a very modular approach, so if you maintain a module, you get to pick the formatter for it, I guess.

I don't know what @KaratekHD prefers, but I don't mind letting people choose what they want because it's very personal at the end.

**Comment by diego-garro** [comment]
Exactly, the idea is that everyone uses the same formatter, so it will be added to `requirements.txt` and automatically installed.

**Comment by why-not-try-calmer** [comment]
> Exactly, the idea is that everyone uses the same formatter, so it will be added to `requirements.txt` and automatically installed.

What I meant is that for me it's better if every one chooses the formatter they prefer _for the modules they maintain_, that is, 1 formatter for 1 module, but perhaps 4 different formatters in total.

**Comment by KaratekHD** [comment]
I didn't use a code formatter before, but for this project I use autopep8. But I think it's ok if everyone choses what they like, like @why-not-try-calmer suggested.

**Comment by why-not-try-calmer** [comment]
Nice. So @diego-garro the idea is not:

- let's make the code base a happy mess

the idea is:

1. the person "responsible" (doing the more work on) module A uses the formatter they want for A.
2. the same person never uses different formatters.

When/if we have 5+ people working a lot with 5+ different formatters, this will not work anymore. But for now it's OK

**Comment by diego-garro** [comment]
Ok guys
